$filePath = "src\app\pages\DashboardPage.tsx"
$content = Get-Content $filePath -Raw

# Remove Habit Tracker card
$content = $content -replace '(?s)            <Card className="rounded-\[28px\] border border-white/70 bg-white/90 p-6 shadow-\[0_28px_90px_rgba\(15,23,42,0\.08\)\]">\s+<div className="flex items-start justify-between gap-4">\s+<div>\s+<p className="text-sm uppercase tracking-\[0\.32em\] text-slate-500">Habit Tracker</p>\s+<h3 className="mt-3 text-2xl font-semibold text-slate-950">Healthy habits</h3>\s+</div>\s+<Activity className="h-6 w-6 text-slate-600" />\s+</div>\s+<div className="mt-8 space-y-5">\s+{habitTracker\.map\(\(item\) => \(\s+<div key={item\.label}>\s+<div className="flex items-center justify-between text-sm font-semibold text-slate-700">\s+<span>{item\.label}</span>\s+<span>{item\.progress}%</span>\s+</div>\s+<div className="mt-3 h-2\.5 rounded-full bg-slate-200 overflow-hidden">\s+<div className={`h-full rounded-full bg-gradient-to-r \${\s*item\.color}`} style={{ width: `\${\s*item\.progress}%` }} />\s+</div>\s+</div>\s+\)\)\s*}\s+</div>\s+</Card>\s*\n\s*', "`n            "

# Remove Journal Preview card
$content = $content -replace '(?s)<Card className="rounded-\[28px\] border border-white/70 bg-white/90 p-6 shadow-\[0_28px_90px_rgba\(15,23,42,0\.08\)\]">\s+<div className="flex items-start justify-between gap-4">\s+<div>\s+<p className="text-sm uppercase tracking-\[0\.32em\] text-slate-500">Journal Preview</p>\s+<h3 className="mt-3 text-2xl font-semibold text-slate-950">Today&apos;s reflection</h3>\s+</div>\s+<BookOpen className="h-6 w-6 text-slate-600" />\s+</div>\s+<div className="mt-8 rounded-\[28px\] border border-slate-200 bg-slate-50 p-5">\s+<p className="text-sm text-slate-600">"Today was more productive than I expected\. The breathing session in the morning really helped me stay calm\."</p>\s+<p className="mt-4 text-xs text-slate-500">4:35 PM</p>\s+</div>\s+<Button onClick={() => navigate\('\/mood'\)} className="mt-6 w-full rounded-full bg-violet-600 text-white hover:bg-violet-700">Continue Writing</Button>\s+</Card>\s*\n\s*', ""

# Remove Sleep Wellness card  
$content = $content -replace '(?s)<Card className="rounded-\[28px\] border border-white/70 bg-white/90 p-6 shadow-\[0_28px_90px_rgba\(15,23,42,0\.08\)\]">\s+<div className="flex items-start justify-between gap-4">\s+<div>\s+<p className="text-sm uppercase tracking-\[0\.32em\] text-slate-500">Sleep Wellness</p>\s+<h3 className="mt-3 text-2xl font-semibold text-slate-950">Rest quality</h3>\s+</div>\s+<Moon className="h-6 w-6 text-slate-600" />\s+</div>\s+<div className="mt-8 space-y-5">.*?</div>\s+</Card>\s*\n\s*(?=<Card className="rounded-\[28px\] border border-white/70 bg-white/90 p-6 shadow-\[0_28px_90px_rgba\(15,23,42,0\.08\)\]">|</div>)', ""

Set-Content $filePath $content
Write-Host "Removed three dashboard cards successfully"
